export const project = {
  name: "La Holanda",
  tagline: "Donde la naturaleza se convierte en tu hogar",
  type: "Parcelación Campestre",
  developer: "INGESOCC SAS",
  location: {
    municipality: "Quimbaya",
    department: "Quindío",
    address: "Vía Quimbaya - Alcalá, Vereda Jazmín",
    distanceToTown: "20 minutos del parque principal de Quimbaya",
  },
  advantages: [
    "Turismo en crecimiento",
    "Alta valorización",
    "Clima agradable",
    "Paisajes naturales",
    "Seguridad",
    "Calidad de vida",
  ],
  purchaseIncludes: [
    "Escritura pública individual",
    "Proceso de legalización",
    "Lote delimitado según el plano",
    "Vía principal de acceso",
    "Diseño arquitectónico tipo incluido",
    "Conservación opcional de árboles de aguacate",
  ],
  constructionServices: [
    "Diseño arquitectónico personalizado",
    "Diseño estructural",
    "Diseño hidrosanitario",
    "Diseño eléctrico",
    "Estudios",
    "Trámites",
    "Licencias de construcción",
    "Presupuesto",
    "Programación",
    "Construcción",
    "Entrega de vivienda",
  ],
  contact: {
    company: "INGESOCC SAS",
    phone: "3217151831",
    email: "gerencia.ingesocc@gmail.com",
    office: "Armenia - Km 6 vía La Tebaida, Bodega 2",
  },
} as const;
