export const project = {
  name: "La Holanda",
  tagline: "Donde la naturaleza se convierte en tu hogar",
  type: "Parcelación Campestre",
  developer: "INGESOCC SAS",
  location: {
    municipality: "Quimbaya",
    department: "Quindío",
    address: "Vía Quimbaya - Alcalá, Vereda Jazmín",
    distanceToTown: "20 minutos del parque principal de Quimbaya",
  },
  advantages: [
    "Turismo en crecimiento",
    "Alta valorización",
    "Clima agradable",
    "Paisajes",
    "Seguridad",
    "Calidad de vida",
  ],
  purchaseIncludes: [
    "Escritura pública individual",
    "Lotes delimitados con cerca viva",
    "Vía interna de acceso",
    "Diseño arquitectónico tipo incluido",
    "Entorno natural con árboles de aguacate",
  ],
  constructionServices: [
    "Diseño arquitectónico personalizado",
    "Paquete completo de diseños (estructural, hidrosanitario, eléctrico)",
    "Estudios, trámites y licencias de construcción",
    "Presupuesto y programación",
    "Construcción",
    "Entrega de la vivienda",
  ],
  contact: {
    company: "INGESOCC SAS",
    phone: "3217151831",
    whatsapp: "573127370811",
    email: "gerencia.ingesocc@gmail.com",
    office: "Armenia – km 6 vía La Tebaida, Bodega 2",
  },
} as const;
